server {
	server_name    geekfarmlife.com www.geekfarmlife.com gflpodcast.com www.gflpodcast.com;
	root           /var/www/geekfarmlife.com;
	index          index.html;

	gzip             on;
	gzip_comp_level  3;
	gzip_types       text/plain text/css application/javascript image/*;

    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/geekfarmlife.com-0001/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/geekfarmlife.com-0001/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

    location = /feed/ {
	    rewrite ^ /rss.xml redirect;
    }	 






}
server {
    if ($host = www.gflpodcast.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    if ($host = gflpodcast.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    if ($host = www.geekfarmlife.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    if ($host = geekfarmlife.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


	listen         80;
	listen         [::]:80;
	server_name    geekfarmlife.com www.geekfarmlife.com gflpodcast.com www.gflpodcast.com;
    return 404; # managed by Certbot








}
