server {
    if ($host = mcp.geekfarmlife.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    listen [::]:80;
    server_name mcp.geekfarmlife.com;

    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    location / {
        return 301 https://$host$request_uri;
    }


}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name mcp.geekfarmlife.com;
    ssl_certificate /etc/letsencrypt/live/geekfarmlife.com-0001/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/geekfarmlife.com-0001/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location = /a8K2mQ9xT4pL7nYs {
        proxy_pass http://127.0.0.1:3001/a8K2mQ9xT4pL7nYs;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Connection '';
        proxy_buffering off;
        proxy_read_timeout 3600s;
    }


    location = /d94651c325106636 {
        proxy_pass http://127.0.0.1:3030/d94651c325106636;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Connection '';
        proxy_buffering off;
        proxy_read_timeout 3600s;
    }

    location = /healthz {
        proxy_pass http://127.0.0.1:3001/healthz;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }

    location / {
        return 404;
    }

}

